name: amikhalev_gen_ai_detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.0.0
  - pandas>=1.5.0
  - numpy>=1.23.0
  - matplotlib>=3.6.0
  - jupyter>=1.0.0
  - scikit-learn>=1.2.0
  - plotly>=5.10.0
  - tqdm>=4.64.0
  - xgboost
  - pip:
    - gdown>=4.6.0
    - torch>=2.0.0
    - transformers>=4.30.0
    - datasets>=2.12.0
    - seaborn>=0.12.0